"""
Alert Model
============

Defines the SQLAlchemy ORM model for security alerts in SentinelAI.

Alerts are generated by the alert engine when:
- The rule engine detects a policy violation
- The ML engine identifies anomalous behavior
- The risk engine flags a critical risk score
- Manual investigation creates a finding

Alert Lifecycle:
    1. Generated -> New alert created by automated detection
    2. Acknowledged -> Analyst has seen the alert
    3. Investigating -> Active investigation underway
    4. Resolved -> Issue addressed and closed
    5. False Positive -> Incorrectly triggered alert

Alert Priorities:
    - low: Informational, no immediate action needed
    - medium: Should be reviewed within 24 hours
    - high: Must be reviewed within 4 hours
    - critical: Requires immediate attention

Database Table: alerts
"""

import uuid
from datetime import datetime
from sqlalchemy import (
    Column, String, DateTime, Integer, Text,
    ForeignKey, Index, Float, Boolean
)
from sqlalchemy.dialects.postgresql import UUID, JSONB
from sqlalchemy.orm import relationship
from app.database.connection import Base


class Alert(Base):
    """
    Security alert model for threat detection notifications.

    Each alert captures a potential security event, its context, the
    risk score at the time of detection, and a human-readable explanation
    of why the alert was triggered. This enables SOC analysts to quickly
    understand and triage threats.

    Attributes:
        id: Primary key (UUID)
        user_id: Foreign key to the user who triggered the alert
        alert_type: Category of the alert
        title: Short alert title
        description: Detailed alert description
        severity: Alert severity level
        priority: Required response priority
        status: Current lifecycle status
        risk_score: Risk score at time of alert generation
        explanation: Explainable AI output describing why this triggered
        recommended_action: Suggested remediation steps
        source: What generated this alert (rule_engine, ml_engine, etc.)
        metadata_json: Additional alert context
        acknowledged_by: Analyst who acknowledged the alert
        acknowledged_at: When the alert was acknowledged
        resolved_by: Who resolved the alert
        resolved_at: When the alert was resolved
        resolution_notes: Notes about the resolution
        is_false_positive: Whether this was determined to be a false positive
        created_at: When the alert was generated
        updated_at: Last modification timestamp
    """
    __tablename__ = "alerts"

    id = Column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        index=True,
        comment="Unique alert identifier"
    )
    user_id = Column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        comment="Foreign key to the user associated with this alert"
    )
    alert_type = Column(
        String(100),
        nullable=False,
        index=True,
        comment="Alert category: anomaly, rule_violation, risk_threshold, etc."
    )
    title = Column(
        String(255),
        nullable=False,
        comment="Short human-readable alert title"
    )
    description = Column(
        Text,
        nullable=True,
        comment="Detailed description of the security event"
    )
    severity = Column(
        String(20),
        nullable=False,
        index=True,
        comment="Severity level: low, medium, high, critical"
    )
    priority = Column(
        String(20),
        default="medium",
        nullable=False,
        comment="Response priority: low, medium, high, critical"
    )
    status = Column(
        String(30),
        default="generated",
        nullable=False,
        index=True,
        comment="Lifecycle status: generated, acknowledged, investigating, resolved, false_positive"
    )
    risk_score = Column(
        Float,
        nullable=True,
        comment="Risk score at time of alert generation (0-100)"
    )
    explanation = Column(
        Text,
        nullable=True,
        comment="Explainable AI output: why this alert was triggered"
    )
    recommended_action = Column(
        Text,
        nullable=True,
        comment="Suggested remediation or investigation steps"
    )
    source = Column(
        String(50),
        nullable=False,
        comment="Detection source: rule_engine, ml_engine, risk_engine, manual"
    )
    metadata_json = Column(
        JSONB,
        nullable=True,
        comment="Additional structured context about the alert"
    )
    acknowledged_by = Column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="SET NULL"),
        nullable=True,
        comment="Foreign key to the analyst who acknowledged the alert"
    )
    acknowledged_at = Column(
        DateTime(timezone=True),
        nullable=True,
        comment="Timestamp when the alert was acknowledged"
    )
    resolved_by = Column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="SET NULL"),
        nullable=True,
        comment="Foreign key to the user who resolved the alert"
    )
    resolved_at = Column(
        DateTime(timezone=True),
        nullable=True,
        comment="Timestamp when the alert was resolved"
    )
    resolution_notes = Column(
        Text,
        nullable=True,
        comment="Notes about how the alert was resolved"
    )
    is_false_positive = Column(
        Boolean,
        default=False,
        nullable=False,
        comment="Whether this alert was determined to be a false positive"
    )
    created_at = Column(
        DateTime(timezone=True),
        default=datetime.utcnow,
        nullable=False,
        index=True,
        comment="When the alert was generated"
    )
    updated_at = Column(
        DateTime(timezone=True),
        default=datetime.utcnow,
        onupdate=datetime.utcnow,
        nullable=False
    )

    __table_args__ = (
        Index("idx_alerts_user_severity", "user_id", "severity"),
        Index("idx_alerts_status_created", "status", "created_at"),
        Index("idx_alerts_type_severity", "alert_type", "severity"),
    )

    # Relationships
    user = relationship(
        "User",
        back_populates="alerts",
        foreign_keys=[user_id],
        lazy="selectin"
    )
    acknowledger = relationship(
        "User",
        foreign_keys=[acknowledged_by],
        lazy="selectin"
    )
    resolver = relationship(
        "User",
        foreign_keys=[resolved_by],
        lazy="selectin"
    )

    def __repr__(self) -> str:
        return (
            f"<Alert(id={self.id}, type='{self.alert_type}', "
            f"severity='{self.severity}', status='{self.status}')>"
        )
